ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
RUBY_PATCHLEVEL = 290
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2011 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '1.9.2'
RUBY_PLATFORM = 'x86_64-darwin10.8.0'
